name: Dependabot
on: pull_request

permissions:
    pull-requests: write
    contents: write

jobs:
    dependabot:
        runs-on: ubuntu-latest
        if: ${{ github.actor == 'dependabot[bot]' }}
        env:
            PR_URL: ${{github.event.pull_request.html_url}}
            GH_TOKEN: ${{github.token}}
        steps:
            - name: approve
              run: gh pr review --approve "$PR_URL"
            - name: merge
              run: gh pr merge --auto --squash --delete-branch "$PR_URL"
